import { Component, OnInit, ViewChild } from '@angular/core';
import { Router } from '@angular/router';
import { FormioComponent } from '@formio/angular';
import { UsersService } from 'src/app/services/users.service';
import { IUserItem } from '../user-item-model';
import { MdbModalRef, MdbModalService } from 'mdb-angular-ui-kit/modal';

@Component({
  selector: 'app-create-user',
  templateUrl: './create-user.component.html',
  styleUrls: ['./create-user.component.scss']
})
export class CreateUserComponent implements OnInit {

  @ViewChild(FormioComponent, { static: false })
  form!: FormioComponent;
  FormData: any = {
    "title": "Create User",
    "components": [{
      "label": "First Name",
      "labelPosition": "top",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "inputMask": "",
      "displayMask": "",
      "allowMultipleMasks": false,
      "customClass": "textbox-style",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": "",
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "blur",
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "minWords": "",
        "maxWords": "",
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "errors": "",
      "key": "firstName",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "textfield",
      "input": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "addons": [],
      "inputType": "text",
      "id": "ehvvtgm"
    }, {
      "label": "Last Name",
      "labelPosition": "top",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "inputMask": "",
      "displayMask": "",
      "allowMultipleMasks": false,
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": "",
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "blur",
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "minWords": "",
        "maxWords": "",
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "errors": "",
      "key": "lastName",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "textfield",
      "input": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "addons": [],
      "inputType": "text",
      "id": "e25hyz"
    }, {
      "label": "Email",
      "labelPosition": "top",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "displayMask": "",
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": "",
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "kickbox": {
        "enabled": true
      },
      "errorLabel": "",
      "errors": "",
      "key": "email",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "email",
      "input": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "inputType": "email",
      "inputMask": "",
      "id": "eza9ob"
    }, {
      "label": "Username",
      "labelPosition": "top",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "displayMask": "",
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": "",
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "blur",
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "kickbox": {
        "enabled": false
      },
      "errorLabel": "",
      "errors": "",
      "key": "username",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "email",
      "input": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "inputType": "email",
      "inputMask": "",
      "id": "ey891p"
    }, {
      "label": "Password",
      "labelPosition": "top",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "displayMask": "",
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "redrawOn": "",
      "clearOnHide": true,
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "blur",
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "pattern": "^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9]).{8,}$",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "errorLabel": "",
      "errors": "",
      "key": "password",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "addons": [],
      "type": "password",
      "input": true,
      "protected": true,
      "multiple": false,
      "defaultValue": null,
      "unique": false,
      "persistent": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "encrypted": false,
      "allowMultipleMasks": false,
      "mask": false,
      "inputType": "text",
      "inputFormat": "plain",
      "inputMask": "",
      "id": "eiq2vk"
    }, {
      "label": "Confirm Password",
      "labelPosition": "top",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "displayMask": "",
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": false,
      "modalEdit": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "redrawOn": "",
      "clearOnHide": true,
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "blur",
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "pattern": "",
        "customMessage": "",
        "custom": "valid=submission.data.confirmPassword==submission.data.password?true:\"Passwords should match\";",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "errorLabel": "",
      "errors": "",
      "key": "confirmPassword",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "addons": [],
      "type": "password",
      "input": true,
      "protected": true,
      "multiple": false,
      "defaultValue": null,
      "unique": false,
      "persistent": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "dbIndex": false,
      "customDefaultValue": "",
      "calculateValue": "",
      "encrypted": false,
      "allowMultipleMasks": false,
      "mask": false,
      "inputType": "text",
      "inputFormat": "plain",
      "inputMask": "",
      "id": "emrmdwi"
    }, {
      "label": "Department",
      "labelPosition": "top",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "prefix": "",
      "suffix": "",
      "widget": {
        "type": "input"
      },
      "inputMask": "",
      "displayMask": "",
      "allowMultipleMasks": false,
      "customClass": "",
      "tabindex": "",
      "autocomplete": "",
      "hidden": false,
      "hideLabel": false,
      "showWordCount": false,
      "showCharCount": false,
      "mask": false,
      "autofocus": false,
      "spellcheck": true,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "defaultValue": "",
      "persistent": true,
      "inputFormat": "plain",
      "protected": false,
      "dbIndex": false,
      "case": "",
      "truncateMultipleSpaces": false,
      "encrypted": false,
      "redrawOn": "",
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "blur",
      "validate": {
        "required": true,
        "minLength": "",
        "maxLength": "",
        "minWords": "",
        "maxWords": "",
        "pattern": "",
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "errors": "",
      "key": "department",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "textfield",
      "input": true,
      "refreshOn": "",
      "dataGridLabel": false,
      "addons": [],
      "inputType": "text",
      "id": "ext18r"
    }, {
      "label": "Roles",
      "labelPosition": "top",
      "widget": "html5",
      "labelWidth": "",
      "labelMargin": "10",
      "placeholder": "",
      "description": "",
      "tooltip": "",
      "customClass": "",
      "tabindex": "",
      "hidden": false,
      "hideLabel": false,
      "uniqueOptions": false,
      "autofocus": false,
      "disabled": false,
      "tableView": true,
      "modalEdit": false,
      "multiple": false,
      "dataSrc": "values",
      "defaultValue": ["ROLE_ADMIN"],
      "data": {
        "values": [{
          "label": "Admin",
          "value": "ROLE_ADMIN"
        }, {
          "label": "User",
          "value": "ROLE_USER"
        }],
        "resource": "",
        "json": "",
        "url": "",
        "custom": ""
      },
      "dataType": "",
      "idPath": "id",
      "valueProperty": "",
      "limit": 100,
      "template": "<span>{{ item.label }}</span>",
      "refreshOn": "",
      "refreshOnBlur": "",
      "clearOnRefresh": false,
      "searchEnabled": true,
      "selectThreshold": 0.3,
      "readOnlyValue": false,
      "customOptions": {},
      "useExactSearch": false,
      "persistent": true,
      "protected": false,
      "dbIndex": false,
      "encrypted": false,
      "clearOnHide": true,
      "customDefaultValue": "",
      "calculateValue": "",
      "calculateServer": false,
      "allowCalculateOverride": false,
      "validateOn": "change",
      "validate": {
        "required": false,
        "onlyAvailableItems": false,
        "customMessage": "",
        "custom": "",
        "customPrivate": false,
        "json": "",
        "strictDateValidation": false,
        "multiple": false,
        "unique": false
      },
      "unique": false,
      "errorLabel": "",
      "errors": "",
      "key": "roles",
      "tags": [],
      "properties": {},
      "conditional": {
        "show": null,
        "when": null,
        "eq": "",
        "json": ""
      },
      "customConditional": "",
      "logic": [],
      "attributes": {},
      "overlay": {
        "style": "",
        "page": "",
        "left": "",
        "top": "",
        "width": "",
        "height": ""
      },
      "type": "select",
      "indexeddb": {
        "filter": {}
      },
      "selectFields": "",
      "searchField": "",
      "searchDebounce": 0.3,
      "minSearch": 0,
      "filter": "",
      "redrawOn": "",
      "input": true,
      "prefix": "",
      "suffix": "",
      "dataGridLabel": false,
      "showCharCount": false,
      "showWordCount": false,
      "allowMultipleMasks": false,
      "addons": [],
      "lazyLoad": true,
      "authenticate": false,
      "ignoreCache": false,
      "fuseOptions": {
        "include": "score",
        "threshold": 0.3
      },
      "id": "ewz3b95"
    }]
  };
  constructor(private userService: UsersService, private router: Router, private modelRef: MdbModalRef<CreateUserComponent>) { }

  ngOnInit(): void {
  }

  onSubmit() {
    this.form.formio.emit('submitButton');

  }

  handleSubmit() {
    console.log(`In handle submit ${JSON.stringify(this.form.formio.submission)}`);
    let submittedData = this.form.formio.submission.data;
    let userObj: IUserItem = {
      first_name: submittedData.firstName,
      last_name: submittedData.lastName,
      email: submittedData.email,
      username: submittedData.username,
      password: submittedData.password,
      department: submittedData.department,
      roles: [{
        id: 1
      }]
    }

    this.userService.createUser(userObj).subscribe({
      next: this.navigateOnSuccess.bind(this), error: this.handleError.bind(this)
    })
  }

  navigateOnSuccess() {
    this.modelRef.close();
    this.router.navigate(['/usersParent']);
  }

  handleError(err: any) {
    console.error(`Error occured while login ${JSON.stringify(err)}`);

  }

  close() {
    this.modelRef.close();
  }
}
